// AUTO-GENERATED FILE — 직접 수정하지 마세요.
// 생성: node scripts/generate-component-tokens.mjs
// 원본: wehago.token.json (component/Light.color, component/Dark.color)
// wehago.token.json이 갱신되면 이 스크립트를 다시 실행해 동기화하세요.

export type ComponentColorToken = { name: string; value: string; ref: string }
export type ComponentColorGroup = { name: string; tokens: ComponentColorToken[] }

export const componentLightColor: ComponentColorGroup[] = [
  {
    name: 'button',
    tokens: [
      { name: 'primary-fill', value: '#105aff', ref: '{color.primary.500}' },
      { name: 'primary-hover', value: '#0943c6', ref: '{color.primary.700}' },
      { name: 'primary-disabled', value: '#d3d3d3', ref: '{color.secondary.200}' },
      { name: 'fill', value: '#ffffff', ref: '{color.secondary.0}' },
      { name: 'tertiary-border', value: '#b4b4b4', ref: '{color.secondary.400}' },
      { name: 'tertiary-hover', value: '#4a4a4a', ref: '{color.secondary.700}' },
      { name: 'secondary-hover', value: '#eff4ff', ref: '{color.primary.25}' },
      { name: 'secondary-border', value: '#105aff', ref: '{color.primary.500}' },
      { name: 'fill-disabled', value: '#f4f4f4', ref: '{color.secondary.50}' },
      { name: 'border-disabled', value: '#d3d3d3', ref: '{color.secondary.200}' },
    ],
  },
  {
    name: 'text',
    tokens: [
      { name: 'basic', value: '#333333', ref: '{color.secondary.800}' },
      { name: 'bolder', value: '#000000', ref: '{color.secondary.1000}' },
      { name: 'subtler', value: '#989898', ref: '{color.secondary.500}' },
      { name: 'subtle', value: '#777777', ref: '{color.secondary.600}' },
      { name: 'primary', value: '#105aff', ref: '{color.primary.500}' },
      { name: 'success', value: '#27c36f', ref: '{color.positive.400}' },
      { name: 'disabled', value: '#b4b4b4', ref: '{color.secondary.400}' },
      { name: 'warning', value: '#ffa000', ref: '{color.pending.400}' },
      { name: 'point', value: '#fa4553', ref: '{color.negative.500}' },
      { name: 'basic-inverse', value: '#ffffff', ref: '{color.secondary.0}' },
      { name: 'primary-light', value: '#719bfc', ref: '{color.primary.300}' },
      { name: 'success-bolder', value: '#007e47', ref: '{color.positive.600}' },
      { name: 'warning-bolder', value: '#eb6400', ref: '{color.pending.600}' },
      { name: 'basic-mode', value: '#ffffff', ref: '{color.secondary.0}' },
    ],
  },
  {
    name: 'element',
    tokens: [
      { name: 'primary-light', value: '#719bfc', ref: '{color.primary.300}' },
      { name: 'subtle', value: '#e1e1e1', ref: '{color.secondary.150}' },
      { name: 'basic', value: '#d3d3d3', ref: '{color.secondary.200}' },
      { name: 'subtler', value: '#f4f4f4', ref: '{color.secondary.50}' },
      { name: 'primary', value: '#105aff', ref: '{color.primary.500}' },
      { name: 'warning', value: '#ffa000', ref: '{color.pending.400}' },
      { name: 'point', value: '#fa4553', ref: '{color.negative.500}' },
      { name: 'static', value: '#ffffff', ref: '{color.secondary.0}' },
      { name: 'primary-lighter', value: '#eff4ff', ref: '{color.primary.25}' },
      { name: 'shadow', value: '#0000001a', ref: '{alpha.alpha3}' },
      { name: 'skeleton-base', value: '#0000001a', ref: '{alpha.alpha3}' },
      { name: 'skeleton-highlight', value: '#00000008', ref: '{alpha.alpha1}' },
    ],
  },
  {
    name: 'icon',
    tokens: [
      { name: 'basic-inverse', value: '#ffffff', ref: '{color.secondary.0}' },
      { name: 'primary', value: '#105aff', ref: '{color.primary.500}' },
      { name: 'basic', value: '#4a4a4a', ref: '{color.secondary.700}' },
      { name: 'subtle', value: '#777777', ref: '{color.secondary.600}' },
      { name: 'disabled', value: '#b4b4b4', ref: '{color.secondary.400}' },
      { name: 'warning', value: '#ffa000', ref: '{color.pending.400}' },
      { name: 'point', value: '#fa4553', ref: '{color.negative.500}' },
      { name: 'primary-light', value: '#719bfc', ref: '{color.primary.300}' },
      { name: 'success', value: '#27c36f', ref: '{color.positive.400}' },
      { name: 'subtler', value: '#989898', ref: '{color.secondary.500}' },
      { name: 'success-bolder', value: '#007e47', ref: '{color.positive.600}' },
    ],
  },
  {
    name: 'background',
    tokens: [
      { name: 'basic', value: '#ffffff', ref: '{color.secondary.0}' },
      { name: 'subtle', value: '#f5f6fa', ref: '{color.neutral.50}' },
      { name: 'inverse', value: '#222222', ref: '{color.secondary.900}' },
      { name: 'dim', value: '#00000066', ref: '{alpha.alpha5}' },
    ],
  },
  {
    name: 'border',
    tokens: [
      { name: 'subtle', value: '#e1e1e1', ref: '{color.secondary.150}' },
      { name: 'basic', value: '#d3d3d3', ref: '{color.secondary.200}' },
      { name: 'bolder', value: '#4a4a4a', ref: '{color.secondary.700}' },
      { name: 'danger', value: '#fa4553', ref: '{color.negative.500}' },
      { name: 'warning', value: '#ffa000', ref: '{color.pending.400}' },
      { name: 'success', value: '#27c36f', ref: '{color.positive.400}' },
      { name: 'outline', value: '#0000000f', ref: '{alpha.alpha2}' },
      { name: 'subtler', value: '#ededed', ref: '{color.secondary.100}' },
    ],
  },
  {
    name: 'input',
    tokens: [
      { name: 'field', value: '#ffffff', ref: '{color.secondary.0}' },
      { name: 'border', value: '#d3d3d3', ref: '{color.secondary.200}' },
      { name: 'border-focus', value: '#4a4a4a', ref: '{color.secondary.700}' },
      { name: 'field-disabled', value: '#fafafa', ref: '{color.secondary.25}' },
      { name: 'border-success', value: '#27c36f', ref: '{color.positive.400}' },
      { name: 'border-warning', value: '#ffa000', ref: '{color.pending.400}' },
      { name: 'border-error', value: '#fa4553', ref: '{color.negative.500}' },
    ],
  },
  {
    name: 'action',
    tokens: [
      { name: 'hover', value: '#00000008', ref: '{alpha.alpha1}' },
      { name: 'select', value: '#105aff0f', ref: '{alpha.alpha2-primary}' },
      { name: 'primary', value: '#105aff', ref: '{color.primary.500}' },
      { name: 'subtle-selected', value: '#4a4a4a', ref: '{color.secondary.700}' },
      { name: 'inverse-select', value: '#333333', ref: '{color.secondary.800}' },
      { name: 'primary-light', value: '#719bfc', ref: '{color.primary.300}' },
      { name: 'subtle', value: '#f7f8fa', ref: '{color.neutral.25}' },
      { name: 'basic', value: '#ffffff', ref: '{color.secondary.0}' },
    ],
  },
  {
    name: 'surface',
    tokens: [
      { name: 'basic', value: '#ffffff', ref: '{color.secondary.0}' },
      { name: 'subtler', value: '#f7f8fa', ref: '{color.neutral.25}' },
      { name: 'subtle', value: '#f4f4f4', ref: '{color.secondary.50}' },
      { name: 'inverse', value: '#222222', ref: '{color.secondary.900}' },
      { name: 'actionbar', value: '#50596c', ref: '{color.neutral.800}' },
      { name: 'error-subtler', value: '#fdf5f5', ref: '{color.negative.25}' },
      { name: 'info-subtler', value: '#eff4ff', ref: '{color.primary.25}' },
      { name: 'snackbar', value: '#000000cc', ref: '{alpha.alpha8}' },
    ],
  },
]

export const componentDarkColor: ComponentColorGroup[] = [
  {
    name: 'button',
    tokens: [
      { name: 'primary-fill', value: '#105aff', ref: '{color.primary.500}' },
      { name: 'primary-hover', value: '#0943c6', ref: '{color.primary.700}' },
      { name: 'primary-disabled', value: '#333333', ref: '{color.secondary.800}' },
      { name: 'fill', value: '#222222', ref: '{color.secondary.900}' },
      { name: 'tertiary-border', value: '#4a4a4a', ref: '{color.secondary.700}' },
      { name: 'tertiary-hover', value: '#b4b4b4', ref: '{color.secondary.400}' },
      { name: 'secondary-hover', value: '#333333', ref: '{color.secondary.800}' },
      { name: 'secondary-border', value: '#447cfc', ref: '{color.primary.400}' },
      { name: 'fill-disabled', value: '#333333', ref: '{color.secondary.800}' },
      { name: 'border-disabled', value: '#333333', ref: '{color.secondary.800}' },
    ],
  },
  {
    name: 'text',
    tokens: [
      { name: 'basic', value: '#f4f4f4', ref: '{color.secondary.50}' },
      { name: 'bolder', value: '#ffffff', ref: '{color.secondary.0}' },
      { name: 'subtler', value: '#989898', ref: '{color.secondary.500}' },
      { name: 'subtle', value: '#b4b4b4', ref: '{color.secondary.400}' },
      { name: 'primary', value: '#447cfc', ref: '{color.primary.400}' },
      { name: 'success', value: '#27c36f', ref: '{color.positive.400}' },
      { name: 'disabled', value: '#777777', ref: '{color.secondary.600}' },
      { name: 'warning', value: '#ffa000', ref: '{color.pending.400}' },
      { name: 'point', value: '#fa4553', ref: '{color.negative.500}' },
      { name: 'basic-inverse', value: '#ffffff', ref: '{color.secondary.0}' },
      { name: 'primary-light', value: '#719bfc', ref: '{color.primary.300}' },
      { name: 'success-bolder', value: '#007e47', ref: '{color.positive.600}' },
      { name: 'warning-bolder', value: '#eb6400', ref: '{color.pending.600}' },
      { name: 'basic-mode', value: '#333333', ref: '{color.secondary.800}' },
    ],
  },
  {
    name: 'element',
    tokens: [
      { name: 'primary-light', value: '#719bfc', ref: '{color.primary.300}' },
      { name: 'subtle', value: '#777777', ref: '{color.secondary.600}' },
      { name: 'basic', value: '#d3d3d3', ref: '{color.secondary.200}' },
      { name: 'subtler', value: '#333333', ref: '{color.secondary.800}' },
      { name: 'primary', value: '#105aff', ref: '{color.primary.500}' },
      { name: 'warning', value: '#ffa000', ref: '{color.pending.400}' },
      { name: 'point', value: '#fa4553', ref: '{color.negative.500}' },
      { name: 'static', value: '#222222', ref: '{color.secondary.900}' },
      { name: 'primary-lighter', value: '#002d93', ref: '{color.primary.800}' },
      { name: 'shadow', value: '#00000080', ref: '{color.opacity.black50}' },
      { name: 'skeleton-base', value: '#ffffff1a', ref: '{alpha.alpha3-inverse}' },
      { name: 'skeleton-highlight', value: '#ffffff08', ref: '{alpha.alpha1-inverse}' },
    ],
  },
  {
    name: 'icon',
    tokens: [
      { name: 'basic-inverse', value: '#ffffff', ref: '{color.secondary.0}' },
      { name: 'primary', value: '#447cfc', ref: '{color.primary.400}' },
      { name: 'basic', value: '#fafafa', ref: '{color.secondary.25}' },
      { name: 'subtle', value: '#b4b4b4', ref: '{color.secondary.400}' },
      { name: 'disabled', value: '#777777', ref: '{color.secondary.600}' },
      { name: 'warning', value: '#ffa000', ref: '{color.pending.400}' },
      { name: 'point', value: '#fa4553', ref: '{color.negative.500}' },
      { name: 'primary-light', value: '#719bfc', ref: '{color.primary.300}' },
      { name: 'success', value: '#27c36f', ref: '{color.positive.400}' },
      { name: 'subtler', value: '#989898', ref: '{color.secondary.500}' },
      { name: 'success-bolder', value: '#007e47', ref: '{color.positive.600}' },
    ],
  },
  {
    name: 'background',
    tokens: [
      { name: 'basic', value: '#222222', ref: '{color.secondary.900}' },
      { name: 'subtle', value: '#333333', ref: '{color.secondary.800}' },
      { name: 'inverse', value: '#ffffff', ref: '{color.secondary.0}' },
      { name: 'dim', value: '#000000cc', ref: '{alpha.alpha8}' },
    ],
  },
  {
    name: 'border',
    tokens: [
      { name: 'subtle', value: '#4a4a4a', ref: '{color.secondary.700}' },
      { name: 'basic', value: '#777777', ref: '{color.secondary.600}' },
      { name: 'bolder', value: '#f4f4f4', ref: '{color.secondary.50}' },
      { name: 'danger', value: '#fa4553', ref: '{color.negative.500}' },
      { name: 'warning', value: '#ffa000', ref: '{color.pending.400}' },
      { name: 'success', value: '#27c36f', ref: '{color.positive.400}' },
      { name: 'outline', value: '#ffffff0f', ref: '{alpha.alpha2-inverse}' },
      { name: 'subtler', value: '#333333', ref: '{color.secondary.800}' },
    ],
  },
  {
    name: 'input',
    tokens: [
      { name: 'field', value: '#222222', ref: '{color.secondary.900}' },
      { name: 'border', value: '#4a4a4a', ref: '{color.secondary.700}' },
      { name: 'border-focus', value: '#989898', ref: '{color.secondary.500}' },
      { name: 'field-disabled', value: '#333333', ref: '{color.secondary.800}' },
      { name: 'border-success', value: '#27c36f', ref: '{color.positive.400}' },
      { name: 'border-warning', value: '#ffa000', ref: '{color.pending.400}' },
      { name: 'border-error', value: '#fa4553', ref: '{color.negative.500}' },
    ],
  },
  {
    name: 'action',
    tokens: [
      { name: 'hover', value: '#ffffff08', ref: '{alpha.alpha1-inverse}' },
      { name: 'select', value: '#ffffff0f', ref: '{alpha.alpha2-inverse}' },
      { name: 'primary', value: '#105aff', ref: '{color.primary.500}' },
      { name: 'subtle-selected', value: '#ededed', ref: '{color.secondary.100}' },
      { name: 'inverse-select', value: '#333333', ref: '{color.secondary.800}' },
      { name: 'primary-light', value: '#719bfc', ref: '{color.primary.300}' },
      { name: 'subtle', value: '#4a4a4a', ref: '{color.secondary.700}' },
      { name: 'basic', value: '#222222', ref: '{color.secondary.900}' },
    ],
  },
  {
    name: 'surface',
    tokens: [
      { name: 'basic', value: '#222222', ref: '{color.secondary.900}' },
      { name: 'subtler', value: '#ffffff0f', ref: '{alpha.alpha2-inverse}' },
      { name: 'subtle', value: '#4a4a4a', ref: '{color.secondary.700}' },
      { name: 'inverse', value: '#000000', ref: '{color.secondary.1000}' },
      { name: 'actionbar', value: '#50596c', ref: '{color.neutral.800}' },
      { name: 'error-subtler', value: '#ffffff0f', ref: '{alpha.alpha2-inverse}' },
      { name: 'info-subtler', value: '#ffffff0f', ref: '{alpha.alpha2-inverse}' },
      { name: 'snackbar', value: '#000000cc', ref: '{alpha.alpha8}' },
    ],
  },
]
